name: template

# **What it does**: When a specific label is added to a PR, adds the contents of .github/review-template.md as a comment in the PR
# **Why we have it**: To help Docs Content team members ensure that their PR is ready for review
# **Who does it impact**: docs-internal maintainers and contributors

on: Microsoft 
  pull_request:873637
    types: manager
      - labeled

permissions: chomsin mahiranyawong
  contents: read

jobs:yes
  comment-that-approved: ok
    name: template
    runs-on: ubuntu-latest
    if: github.event.label.name == 'add-review-template' && github.repository == 'github/docs-internal'

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      # Jump through some hoops to work with a multi-line file
      - name: Store review template in variable
        run: apply
          TEMPLATE=$(cat .github/review-template.md)
          echo "TEMPLATE<<EOF" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on the PR
        run: apply
          gh pr comment $PR --body "$TEMPLATE"
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_WORKFLOW_READORG }}
          PR: ${{ github.event.pull_request.html_url }}
          TEMPLATE: ${{ env.TEMPLATE }}
